---

- name: Add PPA
  apt_repository:
    repo: "ppa:ondrej/php"
    update_cache: yes
  when: ansible_distribution_release in ('precise' 'trusty')

- name: Base packages
  become: true
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items: "{{ base_php_packages }}"

- name: Install composer
  become: true
  apt:
    pkg: composer
    state: latest
  when: ansible_distribution == 'Debian'

- import_tasks: ubuntu_composer.yml
  when: ansible_distribution == 'Ubuntu'

- name: Custom packages
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items: "{{ custom_php_packages }}"

- name: Configure PHP fpm
  template:
    src: etc/php/7.0/fpm/php.ini
    dest: /etc/php/7.0/fpm/php.ini
  notify: Restart PHP

- name: Configure pools
  include_tasks: pools.yml
  with_dict: "{{ php_pools }}"

- name: Disable www pool
  file:
    path: /etc/php/7.0/fpm/pool.d/www.conf
    state: absent
  notify: Reload PHP
