---

- name: Add PPA
  apt_repository:
    repo: "ppa:ondrej/php"
    update_cache: yes
  when: ansible_distribution_release in ('precise' 'trusty')

- name: Dotdeb apt key
  apt_key:
    url: https://www.dotdeb.org/dotdeb.gpg
  when: ansible_distribution_release == 'jessie'

- name: Dotdeb apt repository
  apt_repository:
    repo: deb http://packages.dotdeb.org jessie all
    update_cache: yes
  when: ansible_distribution_release == 'jessie'

- name: Base packages
  become: true
  apt:
    pkg: "{{ base_php_packages }}"
    state: latest

- name: Install composer
  become: true
  apt:
    pkg: composer
    state: latest
  when: ansible_distribution == 'Debian' and ansible_distribution_release != 'jessie'

- import_tasks: composer.yml
  when: ansible_distribution == 'Ubuntu' or ansible_distribution_release == 'jessie'

- name: Custom packages
  apt:
    pkg: "{{ custom_php_packages }}"
    state: latest

- name: Configure PHP fpm
  template:
    src: etc/php/7.0/fpm/php.ini
    dest: /etc/php/7.0/fpm/php.ini
  notify: Restart PHP

- name: Configure pools
  include_tasks: pools.yml
  with_dict: "{{ php_pools }}"

- name: Disable www pool
  file:
    path: /etc/php/7.0/fpm/pool.d/www.conf
    state: absent
  notify: Reload PHP
