---

- name: Requirements
  apt:
    pkg:
      - gnupg2
      - apt-transport-https
    state: present

- name: Add PPA
  apt_repository:
    repo: "ppa:ondrej/php"
    update_cache: yes
  when: ansible_distribution_release in ('precise', 'trusty', 'xenial', 'bionic')

- name: Dotdeb apt key
  apt_key:
    url: https://www.dotdeb.org/dotdeb.gpg
  when: ansible_distribution_release == 'jessie'

- name: Dotdeb apt repository
  apt_repository:
    repo: deb http://packages.dotdeb.org jessie all
    update_cache: yes
  when: ansible_distribution_release == 'jessie'

- name: sury.org apt key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
  when: ansible_distribution_release == 'stretch' and php_version != 7.0

- name: sury.org apt repository
  apt_repository:
    repo: deb https://packages.sury.org/php/ stretch main
    update_cache: yes
  when: ansible_distribution_release == 'stretch' and php_version != 7.0

- name: Base packages
  become: true
  apt:
    pkg: "{{ base_php_packages }}"
    state: present

- name: Install composer
  become: true
  apt:
    pkg: composer
    state: present
  when: ansible_distribution == 'Debian' and ansible_distribution_release != 'jessie'

- import_tasks: composer.yml
  when: ansible_distribution == 'Ubuntu' or ansible_distribution_release == 'jessie'

- name: Custom packages
  apt:
    pkg: "{{ custom_php_packages }}"
    state: present

- name: Configure PHP fpm
  template:
    src: "etc/php/fpm/php.ini"
    dest: "/etc/php/{{ php_version }}/fpm/php.ini"
  notify: Restart PHP

- name: Configure pools
  include_tasks: pools.yml
  with_dict: "{{ php_pools }}"

- name: Disable www pool
  file:
    path: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
    state: absent
  notify: Reload PHP
