---

- name: "Create pool user {{ item.value.user }}"
  no_log: True
  user:
    name: "{{ item.value.user }}"
    createhome: "{{ item.value.createhome | default(False) }}"
    home: "{{ item.value.home | default('/home/' + item.value.user) }}"
    update_password: on_create

- name: "Configure pool {{ item.key }}"
  template:
    src: etc/php/fpm/pool.d/pool.conf.j2
    dest: "/etc/php/{{ php_version}}/fpm/pool.d/{{ item.key }}.conf"
  notify: Reload PHP
